language: c
jobs:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      sudo: required
      before_script:
        - test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
        - bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere
          DO_CMD=sudo bash
    - os: osx
      env: GENERATOR="Unix Makefiles"
      before_script:
        - bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere
          DO_CMD=sudo bash
    - name: Build on windows
      os: windows
      env: GENERATOR="Visual Studio 15 2017 Win64"
      before_script:
        - choco install zstandard --no-progress -y
        - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install.bat')"
        - ls
        - ./install.bat
        - set PATH=%programfiles%\zlib\bin;%PATH%
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere bash
    - name: Build on windows
      os: windows
      env: GENERATOR=Ninja
      before_install:
        - choco install ninja zstandard --no-progress -y
        - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install.bat')"
        - ls
        - ./install.bat
        - set PATH=%programfiles%\zlib\bin;%PATH%
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere bash
addons:
  apt:
    packages:
      - cmake
script:
  - mkdir prefix
  - mkdir build.release
  - cd build.release
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
    ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release
  - cmake --build . --config Release --target install
  - test -e $TRAVIS_BUILD_DIR/prefix/include/bgen/bgen.h
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/bgen/bgen-config.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/bgen/bgen-targets-release.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/bgen/bgen-targets.cmake
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then otool -l $TRAVIS_BUILD_DIR/prefix/lib/libbgen.dylib | grep -q LC_RPATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then test -e $TRAVIS_BUILD_DIR/prefix/lib/libbgen.so; fi
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdfq
  - mkdir build.debug
  - cd build.debug
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON ..
  - cmake --build . --config Debug
  - ctest --output-on-failure -C Debug
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdfq
