name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Running on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install zstd
      shell: bash
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        $SUDO bash -c "$(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/main/install)"

    - name: Install zlib
      if: matrix.os == 'windows-latest'
      run: powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install.bat')"; ./install.bat

    - name: Install almosthere
      shell: bash
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        $SUDO bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/almosthere

    - name: Create Build Environment
      run: cmake -E make_directory '${{runner.workspace}}/build' -E make_directory '${{runner.workspace}}/prefix'

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX='${{runner.workspace}}/prefix'

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

#     - name: Pre-test
#       working-directory: ${{runner.workspace}}/build
#       shell: bash
#       if: matrix.os == 'windows-latest'
#       run: |
#         pwd
#         test/Release/test_assert_interface_2.exe

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        ctest -C $BUILD_TYPE -V --rerun-failed --output-on-failure

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        $SUDO cmake --build . --target install --config $BUILD_TYPE
