name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Running on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install zstd
      shell: bash
      run: sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/main/install)"

    - name: Install almosthere
      shell: bash
      run: sudo bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/almosthere

    - name: Create Build Environment
      run: cmake -E make_directory '${{runner.workspace}}/build' -E make_directory '${{runner.workspace}}/prefix'

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX='${{runner.workspace}}/prefix'

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install --config $BUILD_TYPE
